### ISSUE TITLE
Apple system fonts

### ISSUE THREAD

**Issue by justinpenner** [system-fonts/modern-font-stacks#2]
For backwards compatibility on macOS and iOS browsers, it probably wouldn't hurt to add `-apple-system` and `BlinkMacSystemFont` to the system UI stack.

References:
https://css-tricks.com/snippets/css/system-font-stack/
https://caniuse.com/font-family-system-ui

**Comment by tedw** [comment]
I really appreciate how concise the font stacks are currently, and since `system-ui` support is really good (98% in North America, 96% globally), maybe just providing a link to caniuse.com would suffice. Folks using a browser/OS that doesn’t support `system-ui` would still fallback to `sans-serif`, which I think in many cases would end up being the same font as `system-ui` anyway.

FWIW there used to be some issues with `system-ui` back in 2017 (see this [blog post](https://infinnie.github.io/blog/2017/systemui.html)) but those appear to be resolved now. Bootstrap added it back in 2020 (https://github.com/twbs/bootstrap/pull/30561/files).

@danklammer Really love the site, btw, well done! 👏

**Comment by danklammer** [comment]
Thanks @justinpenner and @tedw!

I appreciate the idea, but I'm going to keep `system-ui` as @tedw suggested. I added a link to caniuse.com to OS support in the [README notes](https://github.com/system-fonts/modern-font-stacks#system-ui).

This resource is designed with progressive enhancement in mind. I see `-apple-system` and `BlinkMacSystemFont` as a patch during a time that needed it. Support for `system-ui` is very good now.
