### ISSUE TITLE
Unclear info: "Key: Currently In Use / Available / Unavailable"

### ISSUE THREAD

**Issue by dylanphantixr** [system-fonts/modern-font-stacks#20]
What does "Currently In Use / Available / Unavailable" each mean?
My first instinct was to hover over each item for an explanation, but I didn't see any.

**Comment by danklammer** [comment]
@dylanphantixr Hope this helps a bit:

---

**Currently In Use:**   
The system font from each font stack currently being displayed.

**Available:**  
The system font from each font stack that is installed on your machine. It's not being used because it is second in line to the one being used. Order in the font stack matters; first gets priority.

**Unavailable:**  
The font is not installed on your machine.
